services: 
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
    ports:
      - "5000:5000"

volumes:
  node_modules_frontend:
  node_modules_backend: